### ISSUE TITLE
count(): Parameter must be an array or an object that implements Countable on pages with a datagrid

### ISSUE THREAD

**Issue by ChristopheSR** [forkcms/library#57]
There seems to be a problem with the compatability with php 7.2 and the code in spoon for the datagrid, due to the following change in this php version: **count()** will now yield a warning on invalid countable types passed to the array_or_countable parameter.
I get an error on each page in the fork cms backend were the datagrids are used. (see screen)

![schermafbeelding 2018-03-08 om 15 53 13](https://user-images.githubusercontent.com/16104135/37158316-632167bc-22eb-11e8-8bab-d892004a4017.png)

**Comment by carakas** [comment]
fixed in #58
